pipeline {
    agent any

    stages {
        stage('clone') {
            steps{
                
            git branch: 'main', url: 'https://github.com/iam-veeramalla/Jenkins-Zero-To-Hero.git'
            
            }
        }
        stage('Build and Run'){
            parallel{
                stage('buildMaven'){
                    agent any
                    tools {
                        maven 'maven'
                    }
                    stages{
                        stage('Maven'){
                            steps{
                                sh 'cd /var/lib/jenkins/workspace/Spring-Boot/java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package'
                            }
                        }
                        
                    }
                }
                stage('SonarAnalysis'){
                    agent any
                    environment {
                        SONAR_SCANNER = tool 'sonar-scanner'
                    }
                    stages{
                        stage('sonar'){
                            steps{
                                sh ''' 
                                $SONAR_SCANNER/bin/sonar-scanner -Dsonar.host.url=http://13.126.157.39:9000/ \
                                -Dsonar.login=sonar_auth_token \
                                -Dsonar.projectKey=spring-boot-app \
                                -Dsonar.projectName=spring-boot-app
                                '''
                            }
                        }
                    }
                }
            }
        }
    }
}
