apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        resources:   // intially try without resource block and check violation error, then try with resource block 
          requests:  // you will able to see pods getting deployed 
            cpu: "100m"
            memory: "250Mi"
          limits:
            cpu: "100m"
            memory: "250Mi"



