apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: app
        image: vinayjadhav/app:replaceImageTag
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "1m"
            memory: "256Mi"
          limits:
            cpu: "2m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: web
  type: LoadBalancer
