apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: dev
spec:
  containers:
  - name: pod-1
    image: nginx
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: '201m'
        memory: '257Mi'

