apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrole-binding-fluent-bit
subjects:
- apiGroup: rbac.authorization.k8s.io 
  kind: ServiceAccount
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-role
  namespace: logging