apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: bad-busybox
  namespace: defaut # if you use default ns you cant create a application , instead use another namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox:v1.35
        name: busybox
        command:
        - "sleep"
        - "3000"
